### ISSUE TITLE
.scale_normalize from lib/preprocess.py

### ISSUE THREAD

**Issue by sdsawtelle** [mikevoets/jama16-retina-replication#15]
Thank you for the repo Mike.

I am following the README instructions to evaluate on a custom data set, but in the first step I do not find `scale_normalize` in the current version of lib/preprocess.py, but I do see it in the oldest version. Should we be using `_resize_and_center_fundus_all` instead?

Thanks!

**Comment by mikevoets** [comment]
You're welcome, Sonya! I'm glad you are interested in our project.

Yes, you're right. The README instructions to apply pre-processing on a custom data set seem to be outdated. I have updated these instructions now.

The method that has replaced `scale_normalize` is `_resize_and_center_fundus_all` indeed. But the proper method to use would be `resize_and_center_fundus` from `lib.preprocess`, which is used as a wrapper around `_resize_and_center_fundus_all`.

**Comment by sdsawtelle** [comment]
Much appreciated Mike!
