### ISSUE TITLE
Regarding EyePACS test image true labels

### ISSUE THREAD

**Issue by gayalkuruppu** [mikevoets/jama16-retina-replication#19]
In[ preprocess_eyepacs.py](https://github.com/mikevoets/jama16-retina-replication/blob/15f2af375c5a581a2002f346efc9a72f4b47f667/preprocess_eyepacs.py#L19), the code uses a `testLabels.csv` file which is not available in the [Kaggle dataset](https://www.kaggle.com/competitions/diabetic-retinopathy-detection/data). There is a new csv file called sampleSubmission.csv instead which does not contain true labels for the images(all labels are class 0). But in the discussion tab of Kaggle, they have provided a file called [retinopathy_solution.csv](https://www.kaggle.com/c/diabetic-retinopathy-detection/discussion/16149#appreciation), which seems like true labels. But some [comments](https://www.kaggle.com/c/diabetic-retinopathy-detection/discussion/16149#1639545) are negative about the labels. So I am having doubts about the authenticity about the labels. Can you provide the true labels for the test images?

A preview of `sampleSubmission.csv` &
> ![Screenshot 2023-02-13 at 10 44 59](https://user-images.githubusercontent.com/46120162/218389212-72f4a7c0-5b01-4b30-9635-df946572eb83.png)

A preview of `retinopathy_solution.csv`

> ![Screenshot 2023-02-13 at 10 46 57](https://user-images.githubusercontent.com/46120162/218389562-f891e83b-1eb4-4bc0-ad53-f907c76c92ae.png)

**Comment by mikevoets** [comment]
Hi there @gayalkuruppu, first of all, thanks for the interest in this project! Yeah, we did get access to the test labels from the EyePACS data set, and they are placed in https://github.com/mikevoets/jama16-retina-replication/tree/master/vendor/eyepacs. 

Note that you only need to place the EyePACS data set in the data directory as-is from Kaggle (i.e. without the test labels). When you run the `eyepacs.sh` Bash script, the script will grab the test labels from the vendor folder, and include these test labels in the TFRecord distribution files for training & testing:

> 3. Run $ ./eyepacs.sh to decompress and preprocess the Kaggle EyePACS data set, and redistribute this set into a training and test set. Run with the --only_gradable flag if you want to train and evaluate with gradable images only. NB: This is a large data set, so this may take hours to finish.

Hope that helps you!
