### ISSUE TITLE
question about eyepacs.sh

### ISSUE THREAD

**Issue by Irish-kw** [mikevoets/jama16-retina-replication#20]
HI:

I'm still not understand after using eyepacs.sh.
I got bin2/pool, two folder, there is grade folder in pool (0/1/2/3/4), but only 0/1 in bin2.

which one can use for training and test ? 
thank you so much

**Comment by mikevoets** [comment]
Hi @Irish-kw,

The EyePACS data set was graded according to the International Clinical Diabetic Retinopathy scale, with no, mild, moderate, severe or proliferative severity. Our neural network however outputs only one binary prediction: moderate or worse diabetic retinopathy (referable diabetic retinopathy).

The `eyepacs.sh` script moves the EyePACS images labeled with 0,1 into the bin2/train/0 and bin2/test/0 folder, and images labeled with 2,3,4 are moved into the bin2/train/1 and bin2/test/1 folder, for training and testing, respectively.

Hope that clears things up!
