### ISSUE TITLE
Empty tf-records files

### ISSUE THREAD

**Issue by agaldran** [mikevoets/jama16-retina-replication#4]
Hi,

I'm sorry about asking this, but I have no knowledge about how tf-records work, and therefore have no clue on how to debug this.

When starting the training, the datasets appear to be empty. After checking the folder `data/eyepacs/bin2/train`, it seems that tf-records files are empty. Would you have a hint on what could have gone wrong here?

![image](https://user-images.githubusercontent.com/4498444/38730531-c6497e76-3f0e-11e8-8623-38eeb6ed8cd0.png)

The same goes for the dimensions.txt file I was mentioning in a previous issue, and also for those `0` and `1` folders, so this may be the root of that problem I had also..

Thank you very much for your help. Cheers,

Adrian

**Comment by mikevoets** [comment]
Hi again! This seems to be the reason why your dimensions.txt file was empty. 

Can you tell me if the directory `data/eyepacs/pool` contains 5 folders [0-4] with images inside?

**Comment by agaldran** [comment]
Hi, thanks for your quick reply, Mike. It does not, it only contains a test and a train folder, and they are empty:

![image](https://user-images.githubusercontent.com/4498444/38735339-7354dff0-3f20-11e8-99b4-40739bc0d8de.png)

Cheers,

Adrian

**Comment by mikevoets** [comment]
Wow, that's strange. Seems like `python preprocess_eyepacs.py --data_dir="$pool_dir"` on line 145 of `eyepacs.sh` did not run. Can you try to run that script with the help flag to verify that you don't get any error on running this Python script? `$ python preprocess_eyepacs.py -h`

**Comment by agaldran** [comment]
Ok, you are right, the python script call was failing silently. The reason was I was missing a dependency on `matplotlib` in my conda environment:

```
ModuleNotFoundError: No module named 'pylab'
```

After installing it, executing `python preprocess_eyepacs.py -h` appears to run smoothly. I am going to try now to re-run the entire `sh` script again.

Many thanks!

**Comment by mikevoets** [comment]
I added matplotlib to the list of dependencies and added a check in the preprocessing script for whether all dependencies are installed or not, so that this will not happen again. Thanks for opening this issue!

**Comment by dragosbratu** [comment]
For me, in windows, providing the full path to the command argument C:/path/to/the/file list fixed the problems(and empty files)
