### ISSUE TITLE
Zeroed out confusion matrix and AUC = 0 during whole training

### ISSUE THREAD

**Issue by temida** [mikevoets/jama16-retina-replication#6]
Hi there,
I am trying to reproduce your experiments in my university's lab and I'm observing some weird behaviour. After successfully following steps in readme regarding preprocessing (excluding Messidor for now) I run `train.py` without any parameters (as you describe it in the aforementioned readme). Cross entropy during training fluctuates naturally, but at the end of every epoch it turns out that Brier score, AUC and, what is more, confusion matrix - they are all filled with zeros :/ Due to the early stopping rule based on AUC training is then interrupted after epoch 10 (see attached [log file](https://github.com/mikevoets/jama16-retina-replication/files/2043040/train1.log)). Any ideas what might have gone so wrong?

My environment:
* OS: CentOS 7.4 x64
* Python: 3.4^
* Tensorflow: 1.5.0
* GPU: NVIDIA Tesla K20m

^_note: Python version is lower than specified in requirements, but I've noticed that the only Python feature forcing the scripts to require version 3.6 is f-string formatting, so I've modified all the print statements to use older {} formatting style._

**Comment by ronnyshalev** [comment]
@temida 
I was wondering if you could help me on the pre-processing step. After running the eyepacs.sh I was left with the folder structure as follows. It does not seem complete and I have no idea how to read the eyepacs.sh file (I have never used linux). If you could tell me what tree structure to expect, I will distribute the files manually.

data/
    eyepacs/
            pool/
                train/                                 <----------- empty folder
                
                10_left.jpeg
                10_right.jpeg
                ... (35,127 image files)

**Comment by ronnyshalev** [comment]
Another attempt to describe the tree I am getting

data/
      eyepacs/
                  pool/
                         train/
                         10_left.jpeg
                         10_right.jpeg
                          ...(35,127 image files)

**Comment by mikevoets** [comment]
@temida Do you still experience this problem with the latest release?

**Comment by mikevoets** [comment]
@ronnyshalev Please open another issue with your problem if you still have this problem with the latest code.
