### ISSUE TITLE
Zeroed out confusion matrix and AUC = 0 during training when trained with gradable images only

### ISSUE THREAD

**Issue by bsabri** [mikevoets/jama16-retina-replication#8]
I'm observing the same issue reported in #6 when I train with gradable images only. When all eyepacs images are used this does not happen

**Comment by ZHULLI** [comment]
@bsabri Hello, I am also doing DR, can you tell me how to do it in data preprocessing? I have a dataset but only when the eyepacs.sh is running, the training set is not preprocessed.

**Comment by mikevoets** [comment]
@bsabri Does this happen every time you train? Or only occasionally?

@ZHULLI What is the exact command you're running? And on what platform?

**Comment by mikevoets** [comment]
Closing this issue for now because I didn't receive enough information to reproduce this issue.
